service: reevoo-shortlink
frameworkVersion: "^1.75.1"
# AWS 的配置
provider:
  name: aws
  runtime: nodejs12.16
  stage: dev
  region: us-east-1
  profile: default
plugins:
  - serverless-finch
# 以下为 serverless-finch 的配置
custom:
  client:
    bucketName: home.rv-s.cn # 需要和 S3 上创建的 bucket 同名
    distributionFolder: build # 本地打包的输出目录
    indexDocument: index.html # 同 S3 上静态文件托管中设置的入口文档
    errorDocument: index.html # 同 S3 上静态文件托管中设置的错误文档